"""autogen_all_modules

Revision ID: 2bd0783d30a8
Revises: 
Create Date: 2026-04-01 14:05:27.979626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd0783d30a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路径'),
    sa.Column('method', sa.String(length=255), nullable=True, comment='方法'),
    sa.Column('group', sa.String(length=255), nullable=True, comment='分组'),
    sa.PrimaryKeyConstraint('id'),
    comment='路由管理'
    )
    op.create_index(op.f('ix_api_deleted_at'), 'api', ['deleted_at'], unique=False)
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(length=255), nullable=False),
    sa.Column('v0', sa.String(length=255), nullable=True),
    sa.Column('v1', sa.String(length=255), nullable=True),
    sa.Column('v2', sa.String(length=255), nullable=True),
    sa.Column('v3', sa.String(length=255), nullable=True),
    sa.Column('v4', sa.String(length=255), nullable=True),
    sa.Column('v5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('file_number', sa.Integer(), nullable=False, comment='文件分片序号'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='上级 ID'),
    sa.Column('file_md5', sa.String(length=100), nullable=False, comment='文件MD5值'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.PrimaryKeyConstraint('id'),
    comment='分片上传任务'
    )
    op.create_index(op.f('ix_chunk_file_deleted_at'), 'chunk_file', ['deleted_at'], unique=False)
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='编码'),
    sa.Column('dictionary_json', sa.JSON(), nullable=True, comment='字典内容'),
    sa.Column('mold', sa.String(length=255), nullable=True, comment='类型'),
    sa.Column('model_name', sa.String(length=255), nullable=True, comment='模型名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典管理'
    )
    op.create_index(op.f('ix_dictionary_deleted_at'), 'dictionary', ['deleted_at'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='文件名称'),
    sa.Column('file_md5', sa.String(length=255), nullable=True, comment='文件md5'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('tag', sa.String(length=255), nullable=True, comment='标签'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('chunk_total', sa.Integer(), nullable=True, comment='文件切片总数'),
    sa.Column('is_done', sa.Boolean(), nullable=True, comment='是否完成'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='所有者ID'),
    sa.Column('owner_type', sa.String(length=50), nullable=True, comment='所有者类型 (表名)'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件管理'
    )
    op.create_index(op.f('ix_document_deleted_at'), 'document', ['deleted_at'], unique=False)
    op.create_table('menu',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路径'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='编码'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='图标'),
    sa.Column('redirect', sa.String(length=255), nullable=True, comment='重定向'),
    sa.Column('active', sa.String(length=255), nullable=True, comment='激活路径'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('link', sa.String(length=255), nullable=True, comment='外链'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='是否隐藏'),
    sa.Column('is_keep_alive', sa.Boolean(), nullable=False, comment='是否缓存'),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('classify', sa.Enum('DIRECTORY', 'MENU', name='menuclassify'), nullable=True, comment='分类'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单管理'
    )
    op.create_index(op.f('ix_menu_deleted_at'), 'menu', ['deleted_at'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='编码'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='角色管理'
    )
    op.create_index(op.f('ix_role_deleted_at'), 'role', ['deleted_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False, comment='用户唯一标识'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('login', sa.String(length=255), nullable=False, comment='登录名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色ID'),
    sa.Column('sex', sa.String(length=255), nullable=True, comment='性别'),
    sa.Column('state', sa.Integer(), nullable=True, comment='状态'),
    sa.Column('layout', sa.JSON(), nullable=True, comment='布局'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户管理'
    )
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_deleted_at'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_menu_deleted_at'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_document_deleted_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_dictionary_deleted_at'), table_name='dictionary')
    op.drop_table('dictionary')
    op.drop_index(op.f('ix_chunk_file_deleted_at'), table_name='chunk_file')
    op.drop_table('chunk_file')
    op.drop_table('casbin_rule')
    op.drop_index(op.f('ix_api_deleted_at'), table_name='api')
    op.drop_table('api')
    # ### end Alembic commands ###
